name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:
  package:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@master
    
    - name: Setup Node 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: package docker
      run: |
        VERSION=$(date +%s)
        docker login docker.pkg.github.com --username mgrabarz --password ${{ secrets.GITHUB_TOKEN }}
        docker build . --file Dockerfile --tag docker.pkg.github.com/mgrabarz/calculator/app:${VERSION}
        docker push docker.pkg.github.com/mgrabarz/calculator/app:${VERSION}
      env:
        CI: true
